version: "3.8"
services:
  php:
    build: ./containers/php-fpm
    volumes:
      - ./backend:/work
  nginx:
    build: ./containers/nginx
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./containers/nginx/laravel.conf:/etc/nginx/conf.d/laravel.conf
  db:
    build: ./containers/mysql
    volumes:
      - DB-store:/var/lib/mysql

volumes:
  DB-store:
